# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: jobreceiver.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11jobreceiver.proto\x12\x0bjobreceiver\"\xf3\x01\n\nJobRequest\x12\x14\n\x0creference_id\x18\x01 \x01(\t\x12\x12\n\nrequest_id\x18\x02 \x01(\x03\x12\x10\n\x08listname\x18\x03 \x01(\t\x12\x15\n\rstructure_ids\x18\x04 \x03(\t\x12\x15\n\rmeta_analysis\x18\x05 \x01(\x08\x12\x0f\n\x07go_term\x18\x06 \x01(\t\x12\x0c\n\x04hash\x18\x07 \x01(\t\x12\x17\n\x0f\x63omparison_mode\x18\x08 \x01(\x05\x12\x15\n\rsegment_start\x18\t \x01(\x05\x12\x13\n\x0bsegment_end\x18\n \x01(\x05\x12\x17\n\x0f\x61lignment_level\x18\x0b \x01(\x05\"#\n\x0cServerStatus\x12\x13\n\x0bstatus_code\x18\x01 \x01(\x05\"\x0f\n\rStatusRequest\"4\n\tJobStatus\x12\x12\n\nrequest_id\x18\x01 \x01(\x03\x12\x13\n\x0bstatus_code\x18\x02 \x01(\x05\"1\n\rResultRequest\x12\x12\n\nrequest_id\x18\x01 \x01(\x03\x12\x0c\n\x04hash\x18\x02 \x01(\t\"X\n\nJobDetails\x12\x12\n\nrequest_id\x18\x01 \x01(\x03\x12\x0c\n\x04hash\x18\x02 \x01(\t\x12\x13\n\x0bsecure_hash\x18\x03 \x01(\t\x12\x13\n\x0bstatus_code\x18\x04 \x01(\x05\"[\n\tJobResult\x12,\n\tfile_info\x18\x01 \x01(\x0b\x32\x17.jobreceiver.JobDetailsH\x00\x12\x14\n\nchunk_data\x18\x02 \x01(\x0cH\x00\x42\n\n\x08job_data\"H\n\x0cUncachedData\x12\x15\n\x0bsecure_hash\x18\x01 \x01(\tH\x00\x12\x14\n\nchunk_data\x18\x02 \x01(\x0cH\x00\x42\x0b\n\tsync_data2\xa5\x02\n\x0bJobReceiver\x12=\n\x08StartJob\x12\x17.jobreceiver.JobRequest\x1a\x16.jobreceiver.JobStatus\"\x00\x12\x44\n\tGetStatus\x12\x1a.jobreceiver.StatusRequest\x1a\x19.jobreceiver.ServerStatus\"\x00\x12H\n\x0e\x44ownloadResult\x12\x1a.jobreceiver.ResultRequest\x1a\x16.jobreceiver.JobResult\"\x00\x30\x01\x12G\n\x0bSynchronize\x12\x19.jobreceiver.UncachedData\x1a\x19.jobreceiver.ServerStatus\"\x00(\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'jobreceiver_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _JOBREQUEST._serialized_start=35
  _JOBREQUEST._serialized_end=278
  _SERVERSTATUS._serialized_start=280
  _SERVERSTATUS._serialized_end=315
  _STATUSREQUEST._serialized_start=317
  _STATUSREQUEST._serialized_end=332
  _JOBSTATUS._serialized_start=334
  _JOBSTATUS._serialized_end=386
  _RESULTREQUEST._serialized_start=388
  _RESULTREQUEST._serialized_end=437
  _JOBDETAILS._serialized_start=439
  _JOBDETAILS._serialized_end=527
  _JOBRESULT._serialized_start=529
  _JOBRESULT._serialized_end=620
  _UNCACHEDDATA._serialized_start=622
  _UNCACHEDDATA._serialized_end=694
  _JOBRECEIVER._serialized_start=697
  _JOBRECEIVER._serialized_end=990
# @@protoc_insertion_point(module_scope)
