name: machaon
channels:
  - conda-forge
  - defaults
dependencies:
  - beautifulsoup4=4.11.1
  - biopython=1.79
  - joblib=1.1.1
  - hdbscan=0.8.27
  - matplotlib=3.7.1
  - pip
  - python=3.8.16
  - requests=2.28.1
  - seaborn=0.12.2
  - setuptools=65.6.3
  - pip:
    - dsspparser==0.1.3
    - kaleido==0.2.1
    - llvmlite==0.39.1
    - lxml==4.6.3
    - numpy==1.23.5
    - open3d==0.13.0
    - pandas==2.0.0
    - pebble==4.6.3
    - plotly==5.3.1
    - pyyaml==6.0
    - rdkit-pypi==2022.9.3
    - scikit-learn==1.0
    - scipy==1.10.0
    - sklearn==0.0
    - tqdm==4.62.3
    - umap-learn==0.5.3
    - urllib3==1.26.14
    - wordcloud==1.8.1
    - parasail==1.3.3
    - protobuf==4.21.12
    - google==3.0.0
    - grpcio==1.53.0
    - psutil==5.9.4
    - ranky==0.3.3
    - networkx==3.0
