# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: features.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x66\x65\x61tures.proto\"4\n\x06\x41ngles\x12\x0c\n\x04mean\x18\x01 \x03(\x02\x12\x0b\n\x03\x63ov\x18\x02 \x03(\x02\x12\x0f\n\x07\x64\x65t_cov\x18\x03 \x01(\x02\"I\n\x08\x46\x65\x61tures\x12\x17\n\x06phipsi\x18\x01 \x01(\x0b\x32\x07.Angles\x12\x11\n\tdistances\x18\x02 \x03(\x02\x12\x11\n\ttriangles\x18\x03 \x01(\x02\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'features_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ANGLES._serialized_start=18
  _ANGLES._serialized_end=70
  _FEATURES._serialized_start=72
  _FEATURES._serialized_end=145
# @@protoc_insertion_point(module_scope)
